import type { IngestEvent } from "./ingest-event.schema";

export const validExamples: Record<string, IngestEvent> = {
  page_view: {
    event_id: "evt_page_001",
    event_name: "page_view",
    event_version: 1,
    timestamp: "2026-04-26T22:10:00.000Z",
    schema_name: "traffic_page_view",
    schema_version: 1,
    session_id: "sess_abc",
    visitor_id: "vis_abc",
    anonymous_id: "vis_abc",
    page_type: "landing",
    utm_source: "facebook",
    utm_campaign: "gelatina_v1",
    metadata_json: {
      url: "https://site.com/landing",
      path: "/landing",
      title: "Landing",
    },
  },
  step_answered: {
    event_id: "evt_step_answered_01",
    event_name: "step_answered",
    event_version: 1,
    timestamp: "2026-04-26T22:10:10.000Z",
    schema_name: "quiz_step_answered",
    schema_version: 1,
    session_id: "sess_abc",
    visitor_id: "vis_abc",
    anonymous_id: "vis_abc",
    funnel_id: "quiz_gelatina",
    step_id: "step_03",
    metadata_json: {
      question_id: "goal",
      answer_id: "perder_peso",
      answer_label: "Perder peso",
      score: 10,
    },
  },
  result_cta_clicked: {
    event_id: "evt_result_cta_01",
    event_name: "result_cta_clicked",
    event_version: 1,
    timestamp: "2026-04-26T22:10:30.000Z",
    schema_name: "quiz_result_cta_clicked",
    schema_version: 1,
    session_id: "sess_abc",
    visitor_id: "vis_abc",
    anonymous_id: "vis_abc",
    funnel_id: "quiz_gelatina",
    metadata_json: {
      cta_id: "result_primary",
      destination: "/checkout",
      offer_id: "front_offer",
    },
  },
  checkout_started: {
    event_id: "evt_checkout_started_01",
    event_name: "checkout_started",
    event_version: 1,
    timestamp: "2026-04-26T22:10:35.000Z",
    schema_name: "checkout_started",
    schema_version: 1,
    session_id: "sess_abc",
    visitor_id: "vis_abc",
    anonymous_id: "vis_abc",
    lead_id: "lead_001",
    funnel_id: "quiz_gelatina",
    metadata_json: {
      offer_id: "front_offer",
      plan_id: "front_monthly",
    },
  },
  checkout_session_created: {
    event_id: "evt_checkout_session_created_01",
    event_name: "checkout_session_created",
    event_version: 1,
    timestamp: "2026-04-26T22:10:36.000Z",
    schema_name: "checkout_session_created",
    schema_version: 1,
    session_id: "sess_abc",
    visitor_id: "vis_abc",
    anonymous_id: "vis_abc",
    lead_id: "lead_001",
    funnel_id: "quiz_gelatina",
    metadata_json: {
      stripe_checkout_session_id: "cs_test_123",
      offer_id: "front_offer",
      plan_id: "front_monthly",
    },
  },
  payment_success: {
    event_id: "stripe:evt_1ABC",
    event_name: "payment_success",
    event_version: 1,
    timestamp: "2026-04-26T22:11:10.000Z",
    schema_name: "stripe_payment_success",
    schema_version: 1,
    session_id: "sess_abc",
    lead_id: "lead_001",
    order_id: "ord_1001",
    revenue: 29.99,
    currency: "EUR",
    metadata_json: {
      stripe_event_id: "evt_1ABC",
      stripe_payment_intent_id: "pi_123",
      stripe_checkout_session_id: "cs_test_123",
      product_id: "prod_front",
    },
  },
  video_progress: {
    event_id: "evt_video_progress_50",
    event_name: "video_progress",
    event_version: 1,
    timestamp: "2026-04-26T22:12:00.000Z",
    schema_name: "vsl_video_progress",
    schema_version: 1,
    session_id: "sess_abc",
    visitor_id: "vis_abc",
    anonymous_id: "vis_abc",
    funnel_id: "quiz_gelatina",
    metadata_json: {
      video_id: "vturb_001",
      progress: 50,
      video_time: 120,
    },
  },
};

export const invalidExamples = {
  missingIdentifiers: {
    payload: {
      event_id: "evt_x",
      event_name: "page_view",
      event_version: 1,
      timestamp: "2026-04-26T22:00:00.000Z",
      schema_name: "traffic_page_view",
      schema_version: 1,
      metadata_json: {},
    },
    reason: "Missing all required identifiers (session_id, visitor_id, anonymous_id, lead_id, user_id).",
  },
  stepAnsweredMissingFields: {
    payload: {
      event_id: "evt_step_1",
      event_name: "step_answered",
      event_version: 1,
      timestamp: "2026-04-26T22:00:00.000Z",
      schema_name: "quiz_step_answered",
      schema_version: 1,
      session_id: "sess_1",
      funnel_id: "quiz_gelatina",
      step_id: "step_02",
      metadata_json: {
        question_id: "goal",
      },
    },
    reason: "step_answered requires metadata_json.answer_id and metadata_json.answer_label.",
  },
  videoProgressInvalidMark: {
    payload: {
      event_id: "evt_v_1",
      event_name: "video_progress",
      event_version: 1,
      timestamp: "2026-04-26T22:00:00.000Z",
      schema_name: "vsl_video_progress",
      schema_version: 1,
      session_id: "sess_1",
      funnel_id: "quiz_gelatina",
      metadata_json: {
        video_id: "vturb_1",
        progress: 60,
      },
    },
    reason: "video_progress.progress accepts only 25, 50, 75, 95.",
  },
  financialMissingMoneyFields: {
    payload: {
      event_id: "stripe:evt_999",
      event_name: "payment_success",
      event_version: 1,
      timestamp: "2026-04-26T22:00:00.000Z",
      schema_name: "stripe_payment_success",
      schema_version: 1,
      session_id: "sess_1",
      metadata_json: {
        stripe_event_id: "evt_999",
      },
    },
    reason: "Financial events require order_id, revenue and currency.",
  },
};
